db:
  type: sqlite
  path: db.sqlite
  # user: root
  # password: 1
  # host: localhost
  # database: todos
  resetonstart: true
server:
  url: "http://localhost:3000"
  port: ":3000"
  cors:
    - "*"